<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Bridge : you &amp; me  | BugFlow</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="generator" content="Hugo 0.57.2" />
    
    
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    

    
    
      <link href="/dist/css/app.d98f2eb6bcd1eaedb7edf166bd16af26.css" rel="stylesheet">
    

    

    
      
    

    

    <meta property="og:title" content="BugFlow" />
<meta property="og:description" content="基础问题 AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;xxx&rsquo; 原因：一般module和attribute的名字没有拼错的情况下，出现这类问题通常是因为这个py文件所在的目录中存在与module同名的py文件，导致python的错误调用。
解决办法：更改文件名。
Keras TypeError: Unexpected keyword argument passed to optimizer: name Traceback (most recent call last): File &quot;visualizing_the_convnet.py&quot;, line 3, in &lt;module&gt; model = load_model(&#39;cats_and_dogs_small_2.h5&#39;) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\engine\saving.py&quot;, line 249, in load_model optimizer_config, custom_objects=custom_objects) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 838, in deserialize printable_module_name=&#39;optimizer&#39;) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py&quot;, line 194, in deserialize_keras_object return cls.from_config(cls_config) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 159, in from_config return cls(**config) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 247, in __init__ super(RMSprop, self)." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://horizonnn.github.io/post/bugflow/" />
<meta property="article:published_time" content="2019-08-25T21:21:34+08:00" />
<meta property="article:modified_time" content="2019-08-25T21:21:34+08:00" />
<meta itemprop="name" content="BugFlow">
<meta itemprop="description" content="基础问题 AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;xxx&rsquo; 原因：一般module和attribute的名字没有拼错的情况下，出现这类问题通常是因为这个py文件所在的目录中存在与module同名的py文件，导致python的错误调用。
解决办法：更改文件名。
Keras TypeError: Unexpected keyword argument passed to optimizer: name Traceback (most recent call last): File &quot;visualizing_the_convnet.py&quot;, line 3, in &lt;module&gt; model = load_model(&#39;cats_and_dogs_small_2.h5&#39;) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\engine\saving.py&quot;, line 249, in load_model optimizer_config, custom_objects=custom_objects) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 838, in deserialize printable_module_name=&#39;optimizer&#39;) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py&quot;, line 194, in deserialize_keras_object return cls.from_config(cls_config) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 159, in from_config return cls(**config) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 247, in __init__ super(RMSprop, self).">


<meta itemprop="datePublished" content="2019-08-25T21:21:34&#43;08:00" />
<meta itemprop="dateModified" content="2019-08-25T21:21:34&#43;08:00" />
<meta itemprop="wordCount" content="122">



<meta itemprop="keywords" content="" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="BugFlow"/>
<meta name="twitter:description" content="基础问题 AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;xxx&rsquo; 原因：一般module和attribute的名字没有拼错的情况下，出现这类问题通常是因为这个py文件所在的目录中存在与module同名的py文件，导致python的错误调用。
解决办法：更改文件名。
Keras TypeError: Unexpected keyword argument passed to optimizer: name Traceback (most recent call last): File &quot;visualizing_the_convnet.py&quot;, line 3, in &lt;module&gt; model = load_model(&#39;cats_and_dogs_small_2.h5&#39;) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\engine\saving.py&quot;, line 249, in load_model optimizer_config, custom_objects=custom_objects) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 838, in deserialize printable_module_name=&#39;optimizer&#39;) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py&quot;, line 194, in deserialize_keras_object return cls.from_config(cls_config) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 159, in from_config return cls(**config) File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 247, in __init__ super(RMSprop, self)."/>

  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  <header>
    <div class="bg-black">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="https://horizonnn.github.io/" class="f3 fw2 hover-white no-underline white-90 dib">
      Bridge : you &amp; me
    </a>
    <div class="flex-l items-center">
      

      
        <ul class="pl0 mr3">
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/post/" title="Posts page">
              Posts
            </a>
          </li>
          
        </ul>
      
      











    </div>
  </div>
</nav>

    </div>
  </header>



    <main class="pb7" role="main">
      
  
  <article class="flex-l flex-wrap justify-between mw8 center ph3">

    <header class="mt4 w-100">
      <p class="f6 b helvetica tracked">
          
        POSTS
      </p>
      <h1 class="f1 athelas mb1">BugFlow</h1>
      
      <time class="f6 mv4 dib tracked" datetime="2019-08-25T21:21:34&#43;08:00">August 25, 2019</time>
      
      
    </header>

    <section class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray pr4-l w-two-thirds-l">

<h1 id="基础问题">基础问题</h1>

<h3 id="attributeerror-module-xxx-has-no-attribute-xxx">AttributeError: module &lsquo;XXX&rsquo; has no attribute &lsquo;xxx&rsquo;</h3>

<p>原因：一般module和attribute的名字没有拼错的情况下，出现这类问题通常是因为这个py文件所在的目录中存在与module同名的py文件，导致python的错误调用。</p>

<p>解决办法：更改文件名。</p>

<h1 id="keras">Keras</h1>

<h3 id="typeerror-unexpected-keyword-argument-passed-to-optimizer-name">TypeError: Unexpected keyword argument passed to optimizer: name</h3>

<pre><code class="language-shell">Traceback (most recent call last):
  File &quot;visualizing_the_convnet.py&quot;, line 3, in &lt;module&gt;
    model = load_model('cats_and_dogs_small_2.h5')
  File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\engine\saving.py&quot;, line 249, in load_model
    optimizer_config, custom_objects=custom_objects)
  File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 838, in deserialize
    printable_module_name='optimizer')
  File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py&quot;, line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 159, in from_config
    return cls(**config)
  File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 247, in __init__
    super(RMSprop, self).__init__(**kwargs)
  File &quot;D:\ProgramFiles\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\keras\optimizers.py&quot;, line 68, in __init__
    'passed to optimizer: ' + str(k))
TypeError: Unexpected keyword argument passed to optimizer: name
</code></pre>

<p>原因：这部分代码加载了H5文件保存的keras Model，但是由于保存Model和加载Model的keras的版本不一致，所以会产生这个问题</p>

<p>解决办法：保持加载Model和保存Model的keras版本一致</p>

<h3 id="failed-to-create-cublas-handle-cublas-status-alloc-failed">failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED</h3>

<p>原因：申请GPU内存，空间不够被拒绝</p>

<p>解决办法：在代码中加入动态申请内存的显式设定</p>

<pre><code class="language-python">config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)
</code></pre>

<h1 id="matplotlib">matplotlib</h1>

<h3 id="调用imshow-显示出的图像全白">调用imshow()显示出的图像全白</h3>

<p>原因：imshow可以接受float或者int类型的参数，其有效范围分别为[0,1]和[0,255]。当参数类型为float时，imshow会默认将其裁剪到[0,1]的区间内。所以通常是输入了按照[0,255]的区间范围的float参数会出现上述问题</p>

<p>解决办法：将float参数手动转换到[0,1]区间（x = x / 255），或者将其转换为int类型（x = x.astype(&lsquo;int32&rsquo;)）。</p>
<ul class="pa0">
  
</ul>
<div class="mt6">
      
      
      </div>
    </section>

    <aside class="w-30-l mt6-l">




</aside>

  </article>

    </main>
    <footer class="bg-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="https://horizonnn.github.io/" >
    &copy; 2019 Bridge : you &amp; me
  </a>
    <div>










</div>
  </div>
</footer>

    

  <script src="/dist/js/app.3fc0f988d21662902933.js"></script>


  </body>
</html>
